from __future__ import annotations

import os
from typing import Literal

Locale = Literal["en", "es"]

_EN: dict[str, str] = {
    "cli.description": "Read-only diagnostics for SteamOS, Decky Loader, plugins, and Flatpak.",
    "cli.json": "Print machine-readable JSON",
    "cli.no_network": "Skip checks that need the internet",
    "cli.output": "Report path (for the report command)",
    "cli.command": "diagnose (default) or report",
    "cli.ascii": "Use ASCII status marks (OK/X/!) instead of Unicode",
    "cli.only": "Run only these check IDs (comma-separated)",
    "cli.timeout": "Global deadline in seconds (0 disables). Default: 60",
    "cli.lang": "UI language: en or es (default: from LANG)",
    "skip.no_network": "Skipped (--no-network)",
    "skip.no_network.explain": "This check needs the network or a remote query.",
    "skip.only": "Skipped (--only)",
    "skip.only.explain": "Not in the --only list.",
    "skip.timeout": "Skipped (global timeout)",
    "skip.timeout.explain": "DeckDoctor hit the global deadline; remaining checks were not run.",
    "group.system": "System",
    "group.decky": "Decky Loader",
    "group.plugins": "Plugins",
    "group.flatpak": "Flatpak",
    "group.network": "Network",
    "ui.diagnosis": "Diagnosis",
    "ui.fact": "FACT",
    "ui.likely": "LIKELY CAUSE",
    "ui.recommended": "Recommended: {text}",
    "ui.problems": "Problems found: {count}",
    "ui.no_problems": "No FAIL or WARNING checks.",
    "ui.partial": "Partial run: some checks were skipped after the global timeout.",
    "ui.report_hint": "Run `deckdoctor report` for a sanitised diagnostic report.",
    "ui.readonly": "DeckDoctor is read-only: it does not restart services, update Flatpaks, or upload data.",
    "ui.wrote": "Wrote {path}",
    "ui.internal_error": "deckdoctor: internal error: {exc}",
    "report.title": "# DeckDoctor report",
    "report.posture": "- Posture: read-only, local-first, no telemetry.",
    "report.sanitise": "- Sanitisation is **best-effort**. Review this file before posting.",
    "report.system": "## System",
    "report.summary": "## Check summary",
    "report.diagnoses": "## Diagnoses",
    "report.no_diagnoses": "_No correlated diagnoses._",
    "report.problems": "## Failed and warning checks",
    "report.none": "_None._",
    "report.network": "## Network checks performed",
    "report.network.body": (
        "DeckDoctor only contacts endpoints required by explicit checks: GitHub "
        "(github.com, api.github.com/rate_limit, optional releases/latest redirect), "
        "the Decky Plugin Store, Flatpak remotes already configured on the device, "
        "and SteamOS updater endpoints if those tools query them. Nothing is uploaded."
    ),
    "report.plugins": "## Plugins",
    "report.no_plugins": "_None detected._",
    "report.overlay": "## Overlay-edited SteamOS files",
    "report.cef": "## CEF / steamloopback.host excerpt",
    "report.no_cef": "_No CEF target list captured._",
    "report.eol": "## Flatpak end-of-life",
    "report.footer": "This report was generated by DeckDoctor. It does not restart services, apply updates, or modify permissions.",
    "diag.incomplete_rate.title": "Incomplete Decky install and GitHub rate limit",
    "diag.incomplete_rate.summary": (
        "FACT: PluginLoader is missing. FACT: GitHub API remaining is 0. "
        "LIKELY CAUSE: the installer could not download PluginLoader because the unauthenticated "
        "GitHub API quota was exhausted (common on CGNAT)."
    ),
    "diag.incomplete_rate.rec": (
        "Wait for the quota reset or switch networks, then reinstall with the official Decky installer. "
        "Do not delete ~/homebrew/plugins unless you intend to. DeckDoctor will not reinstall Decky."
    ),
    "diag.unit_429.title": "systemd unit replaced by GitHub 429 page",
    "diag.unit_429.summary": (
        "FACT: plugin_loader.service contains GitHub's rate-limit HTML. "
        "The installer saved an API error as a unit file, so Decky cannot start."
    ),
    "diag.unit_429.rec": (
        "Reinstall Decky after GitHub API quota recovers. "
        "Do not hand-edit a 429 page into a valid unit unless you know systemd."
    ),
    "diag.incomplete.title": "Incomplete Decky installation",
    "diag.incomplete.summary": "FACT: the homebrew tree exists but PluginLoader was never downloaded.",
    "diag.incomplete.rec": "Re-run the official installer. If it failed before, check NET-GITHUB first.",
    "diag.port.title": "Decky cannot inject: port 8080 conflict",
    "diag.port.summary": (
        "FACT: PluginLoader is present but port 8080 is not Steam's CEF debugger. "
        "Decky injects through localhost:8080; another process is in the way."
    ),
    "diag.port.rec": "Move the conflicting app (Syncthing should use 8384). DeckDoctor will not kill processes.",
    "diag.steam_beta.title": "Backend healthy; frontend may be a Steam client issue",
    "diag.steam_beta.summary": (
        "FACT: PluginLoader is present and plugin_loader.service is active. "
        "FACT: localhost:8080/json looks like Steam CEF. "
        "FACT: Steam client channel appears to be Beta. "
        "LIKELY CAUSE (medium): the Steam client/frontend, not a broken Decky install. "
        "DeckDoctor cannot see whether the QAM tab is actually missing."
    ),
    "diag.steam_beta.rec": (
        "Contrast with Steam Deck Stable, update Decky, and if React error #130 persists, "
        "disable plugins from Desktop Mode."
    ),
    "diag.autoflatpaks.title": "AutoFlatpaks is fine; Flatpak remote listing is not",
    "diag.autoflatpaks.summary": (
        "FACT: AutoFlatpaks is installed. FACT: `flatpak` works. "
        "FACT: `flatpak remote-ls` failed. "
        "The plugin cannot display a remote package list because Flatpak cannot produce one."
    ),
    "diag.autoflatpaks.rec": "Fix or remove the failing Flatpak remote yourself. DeckDoctor will not delete remotes.",
    "diag.overlay.title": "User-overlaid atomupd/rauc config and updater failure",
    "diag.overlay.summary": (
        "FACT: client.conf and/or rauc/system.conf exist under the SteamOS /etc overlay. "
        "FACT: the SteamOS updater could not complete a read-only check. "
        "LIKELY CAUSE (medium): those overlay copies are hiding the image configs the updater expects."
    ),
    "diag.overlay.rec": (
        "If you edited those files, restore the image copies rather than hand-tuning them. "
        "DeckDoctor will not delete overlay files."
    ),
}

_ES: dict[str, str] = {
    "cli.description": "Diagnóstico de solo lectura para SteamOS, Decky Loader, plugins y Flatpak.",
    "cli.json": "Imprimir JSON legible por máquina",
    "cli.no_network": "Omitir comprobaciones que necesitan Internet",
    "cli.output": "Ruta del informe (comando report)",
    "cli.command": "diagnose (por defecto) o report",
    "cli.ascii": "Usar marcas ASCII (OK/X/!) en lugar de Unicode",
    "cli.only": "Ejecutar solo estos IDs de check (separados por comas)",
    "cli.timeout": "Límite global en segundos (0 lo desactiva). Por defecto: 60",
    "cli.lang": "Idioma de la interfaz: en o es (por defecto: LANG)",
    "skip.no_network": "Omitido (--no-network)",
    "skip.no_network.explain": "Esta comprobación necesita red o una consulta remota.",
    "skip.only": "Omitido (--only)",
    "skip.only.explain": "No está en la lista --only.",
    "skip.timeout": "Omitido (tiempo global agotado)",
    "skip.timeout.explain": "DeckDoctor alcanzó el límite global; no se ejecutaron el resto de checks.",
    "group.system": "Sistema",
    "group.decky": "Decky Loader",
    "group.plugins": "Plugins",
    "group.flatpak": "Flatpak",
    "group.network": "Red",
    "ui.diagnosis": "Diagnóstico",
    "ui.fact": "HECHO",
    "ui.likely": "CAUSA PROBABLE",
    "ui.recommended": "Recomendado: {text}",
    "ui.problems": "Problemas encontrados: {count}",
    "ui.no_problems": "Ningún check en FAIL o WARNING.",
    "ui.partial": "Ejecución parcial: se omitieron checks al agotar el tiempo global.",
    "ui.report_hint": "Ejecuta `deckdoctor report` para un informe de diagnóstico sanitizado.",
    "ui.readonly": "DeckDoctor es de solo lectura: no reinicia servicios, no actualiza Flatpaks ni sube datos.",
    "ui.wrote": "Escrito {path}",
    "ui.internal_error": "deckdoctor: error interno: {exc}",
    "report.title": "# Informe DeckDoctor",
    "report.posture": "- Postura: solo lectura, local, sin telemetría.",
    "report.sanitise": "- La sanitización es **de mejor esfuerzo**. Revisa este archivo antes de publicarlo.",
    "report.system": "## Sistema",
    "report.summary": "## Resumen de checks",
    "report.diagnoses": "## Diagnósticos",
    "report.no_diagnoses": "_Sin diagnósticos correlacionados._",
    "report.problems": "## Checks fallidos y advertencias",
    "report.none": "_Ninguno._",
    "report.network": "## Comprobaciones de red realizadas",
    "report.network.body": (
        "DeckDoctor solo contacta los endpoints que piden checks explícitos: GitHub "
        "(github.com, api.github.com/rate_limit, redirección opcional de releases/latest), "
        "la tienda de plugins de Decky, los remotos Flatpak ya configurados en el dispositivo "
        "y los endpoints del actualizador de SteamOS si esas herramientas los consultan. No se sube nada."
    ),
    "report.plugins": "## Plugins",
    "report.no_plugins": "_Ninguno detectado._",
    "report.overlay": "## Archivos de SteamOS editados en el overlay",
    "report.cef": "## Extracto CEF / steamloopback.host",
    "report.no_cef": "_No se capturó la lista de destinos CEF._",
    "report.eol": "## Flatpak en fin de vida",
    "report.footer": "Este informe lo generó DeckDoctor. No reinicia servicios, no aplica actualizaciones ni cambia permisos.",
    "diag.incomplete_rate.title": "Instalación incompleta de Decky y límite de GitHub",
    "diag.incomplete_rate.summary": (
        "HECHO: falta PluginLoader. HECHO: la cuota de la API de GitHub restante es 0. "
        "CAUSA PROBABLE: el instalador no pudo descargar PluginLoader porque se agotó la cuota "
        "no autenticada de GitHub (habitual en CGNAT)."
    ),
    "diag.incomplete_rate.rec": (
        "Espera a que se reinicie la cuota o cambia de red y reinstala con el instalador oficial de Decky. "
        "No borres ~/homebrew/plugins salvo que sea a propósito. DeckDoctor no reinstala Decky."
    ),
    "diag.unit_429.title": "La unidad systemd fue sustituida por una página 429 de GitHub",
    "diag.unit_429.summary": (
        "HECHO: plugin_loader.service contiene el HTML de límite de GitHub. "
        "El instalador guardó un error de API como archivo de unidad, así que Decky no puede arrancar."
    ),
    "diag.unit_429.rec": (
        "Reinstala Decky cuando se recupere la cuota de GitHub. "
        "No conviertas a mano una página 429 en una unidad válida salvo que sepas systemd."
    ),
    "diag.incomplete.title": "Instalación incompleta de Decky",
    "diag.incomplete.summary": "HECHO: existe el árbol homebrew pero PluginLoader nunca se descargó.",
    "diag.incomplete.rec": "Vuelve a ejecutar el instalador oficial. Si falló antes, mira primero NET-GITHUB.",
    "diag.port.title": "Decky no puede inyectarse: conflicto en el puerto 8080",
    "diag.port.summary": (
        "HECHO: PluginLoader está presente pero el puerto 8080 no es el depurador CEF de Steam. "
        "Decky inyecta a través de localhost:8080; otro proceso lo ocupa."
    ),
    "diag.port.rec": "Mueve la app en conflicto (Syncthing debería usar 8384). DeckDoctor no mata procesos.",
    "diag.steam_beta.title": "El backend está sano; el frontend puede ser un problema del cliente Steam",
    "diag.steam_beta.summary": (
        "HECHO: PluginLoader está presente y plugin_loader.service está activo. "
        "HECHO: localhost:8080/json parece CEF de Steam. "
        "HECHO: el canal del cliente Steam parece Beta. "
        "CAUSA PROBABLE (media): el cliente/frontend de Steam, no una instalación rota de Decky. "
        "DeckDoctor no puede ver si falta la pestaña del QAM."
    ),
    "diag.steam_beta.rec": (
        "Contrasta con Steam Deck Stable, actualiza Decky y, si persiste el error de React #130, "
        "desactiva plugins desde el modo escritorio."
    ),
    "diag.autoflatpaks.title": "AutoFlatpaks está bien; el listado remoto de Flatpak no",
    "diag.autoflatpaks.summary": (
        "HECHO: AutoFlatpaks está instalado. HECHO: `flatpak` funciona. "
        "HECHO: `flatpak remote-ls` falló. "
        "El plugin no puede mostrar el listado remoto porque Flatpak no puede generarlo."
    ),
    "diag.autoflatpaks.rec": "Repara o elimina tú el remoto Flatpak que falla. DeckDoctor no borra remotos.",
    "diag.overlay.title": "Config atomupd/rauc en overlay y fallo del actualizador",
    "diag.overlay.summary": (
        "HECHO: client.conf y/o rauc/system.conf existen en el overlay /etc de SteamOS. "
        "HECHO: el actualizador de SteamOS no pudo completar una consulta de solo lectura. "
        "CAUSA PROBABLE (media): esas copias del overlay ocultan las configs de la imagen que el actualizador espera."
    ),
    "diag.overlay.rec": (
        "Si editaste esos archivos, restaura las copias de la imagen en lugar de retocarlas a mano. "
        "DeckDoctor no borra archivos del overlay."
    ),
}

MESSAGES: dict[str, dict[str, str]] = {"en": _EN, "es": _ES}


def detect_locale(explicit: str | None = None) -> Locale:
    if explicit in {"en", "es"}:
        return explicit  # type: ignore[return-value]
    for key in ("DECKDOCTOR_LANG", "LC_ALL", "LC_MESSAGES", "LANG"):
        raw = os.environ.get(key) or ""
        lowered = raw.lower().replace("-", "_")
        if lowered.startswith("es"):
            return "es"
        if lowered.startswith("en"):
            return "en"
    return "en"


def translate(locale: str, key: str, **kwargs: object) -> str:
    table = MESSAGES.get(locale) or MESSAGES["en"]
    tmpl = table.get(key) or MESSAGES["en"].get(key) or key
    if kwargs:
        return tmpl.format(**kwargs)
    return tmpl
