from __future__ import annotations

from deckdoctor.models import Report, Status
from deckdoctor.sanitizer import Sanitizer


def render_markdown(report: Report, sanitizer: Sanitizer) -> str:
    raw = _markdown(report)
    return sanitizer.apply(raw)


def _markdown(report: Report) -> str:
    lines = [
        "# DeckDoctor report",
        "",
        f"- Tool version: `{report.version}`",
        f"- Generated (UTC): `{report.generated_at}`",
        "- Posture: read-only, local-first, no telemetry.",
        "- Sanitisation is **best-effort**. Review this file before posting.",
        "",
        "## System",
        "",
        f"- User home (sanitised later): `{report.facts.get('decky_home', '')}`",
        f"- SteamOS version: `{report.facts.get('os_version', 'unknown')}` build `{report.facts.get('os_build', 'unknown')}`",
        f"- SteamOS channel: `{report.facts.get('os_channel', 'unknown')}`",
        f"- Steam client: build `{report.facts.get('steam_version', 'unknown')}` channel `{report.facts.get('steam_channel', 'unknown')}`",
        f"- Decky: `{report.facts.get('decky_version', 'unknown')}` channel `{report.facts.get('decky_channel', 'unknown')}`",
        f"- PluginLoader present: `{report.facts.get('plugin_loader_present', 'unknown')}`",
        "",
        "## Check summary",
        "",
        "| Status | ID | Finding |",
        "|---|---|---|",
    ]
    for item in report.results:
        finding = item.finding.replace("|", "\\|")
        lines.append(f"| `{item.status.value}` | `{item.check_id}` | {finding} |")

    lines += ["", "## Diagnoses", ""]
    if not report.diagnoses:
        lines.append("_No correlated diagnoses._")
    for diag in report.diagnoses:
        lines.append(f"### {diag.title}")
        lines.append("")
        lines.append(f"- Kind: **{diag.fact_kind}** · confidence **{diag.confidence.value}** · severity **{diag.severity.value}**")
        lines.append(f"- Checks: {', '.join(f'`{c}`' for c in diag.related_checks)}")
        lines.append("")
        lines.append(diag.summary)
        lines.append("")
        if diag.recommendation:
            lines.append(f"**Recommended:** {diag.recommendation}")
            lines.append("")

    lines += ["", "## Failed and warning checks", ""]
    problems = [r for r in report.results if r.status in {Status.FAIL, Status.WARNING}]
    if not problems:
        lines.append("_None._")
    for item in problems:
        lines.append(f"### {item.check_id}: {item.finding}")
        lines.append("")
        lines.append(f"- Status: `{item.status.value}` · severity `{item.severity.value}` · source `{item.source.value}`")
        if item.explanation:
            lines.append("")
            lines.append(item.explanation)
        if item.recommendation:
            lines.append("")
            lines.append(f"**Recommended:** {item.recommendation}")
        if item.evidence:
            lines.append("")
            lines.append("Evidence:")
            lines.append("")
            lines.append("```")
            lines.extend(item.evidence[:40])
            lines.append("```")
        lines.append("")

    lines += [
        "## Network checks performed",
        "",
        "DeckDoctor only contacts endpoints required by explicit checks: GitHub (github.com, api.github.com/rate_limit, optional releases/latest redirect), the Decky Plugin Store, Flatpak remotes already configured on the device, and SteamOS updater endpoints if those tools query them. Nothing is uploaded.",
        "",
        "## Plugins",
        "",
    ]
    plugins = report.facts.get("plugins") or []
    if not plugins:
        lines.append("_None detected._")
    else:
        lines.append("| Name | Version | Directory |")
        lines.append("|---|---|---|")
        for plugin in plugins:
            lines.append(f"| {plugin.get('name')} | {plugin.get('version')} | `{plugin.get('dir')}` |")

    lines += [
        "",
        "---",
        "",
        "This report was generated by DeckDoctor. It does not restart services, apply updates, or modify permissions.",
        "",
    ]
    return "\n".join(lines)
